# master playbook
- hosts: all
  roles:
    - common
  become: true

- hosts: nginx
  roles:
    - nginx
  become: true

- hosts: kafka_broker_nodes
  roles:
    - kafka-sw
  become: true

- hosts: kafka_broker_nodes
  roles:
    - zookeeper
  become: true

- hosts: kafka_broker_nodes
  roles:
    - kafka-broker
  become: true