- name: Create kafka group
  group:
    name: kafka

- name: Create kafka user
  user:
    name: kafka
    group: kafka

- name: Download Apache Kafka
  get_url:
    url: http://apache.rediris.es/kafka/1.1.0/kafka_2.11-1.1.0.tgz
    dest: /tmp/
    mode: 0755

- name: Untar Kafka
  unarchive:
    src: /tmp/kafka_2.11-1.1.0.tgz
    dest: /opt
    remote_src: yes

- name: Create kafka symbolic link
  file:
    src: /opt/kafka_2.11-1.1.0
    dest: /opt/kafka
    owner: kafka
    group: kafka
    state: link

- name: Creates kafka log dir
  file:
    path: /opt/kafka/logs
    state: directory

- name: Setup owner/group and permissions
  file:
    path: /opt/kafka_2.11-1.1.0
    owner: kafka
    group: kafka
    mode: 0755
    recurse: yes

- name: Configure Zookeeper server (zookeeper.properties)
  template:
    src: zookeeper.properties.j2
    dest: /opt/kafka/config/zookeeper.properties

- name: Creates Zookeeper dir
  file:
    path: /var/lib/zookeeper
    state: directory

- name: Configure Zookeeper myid
  template:
    src: myid.j2
    dest: /var/lib/zookeeper/myid

- name: Start Zookeeper server
  command: /opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties -d

- name: Configure Kafka server (server.properties)
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties

- name: Start Kafka server
  command: /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties -d